# Generated by Django 4.1 on 2024-02-27 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Biografia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("contenido", models.TextField()),
                (
                    "imagenes",
                    models.ImageField(blank=True, null=True, upload_to="biografias/"),
                ),
            ],
        ),
    ]
