# Generated by Django 4.1 on 2024-03-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("biografia", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="biografia",
            name="es_visible",
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
