# Generated by Django 4.1 on 2024-03-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("biografia", "0002_biografia_es_visible"),
    ]

    operations = [
        migrations.AlterField(
            model_name="biografia",
            name="imagenes",
            field=models.ImageField(blank=True, null=True, upload_to="biografia/fotos"),
        ),
    ]
