# Generated by Django 4.1 on 2024-05-07 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carrito", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemcarrito",
            name="cantidad",
            field=models.IntegerField(default=0),
        ),
    ]
