# Generated by Django 4.1 on 2024-05-04 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="descuento",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="producto",
            name="descuento_activo",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="producto",
            name="modelo",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="producto",
            name="tallas",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
