# Generated by Django 4.1 on 2024-05-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0002_producto_descuento_producto_descuento_activo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="tallas",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
