# Generated by Django 4.1 on 2024-03-02 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0002_artista_imagen"),
        ("musica", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cancion",
            name="artista",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="booking.artista"
            ),
        ),
    ]
