# Generated by Django 4.1 on 2024-03-02 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("musica", "0002_alter_cancion_artista"),
    ]

    operations = [
        migrations.AddField(
            model_name="cancion",
            name="archivo_audio",
            field=models.FileField(default=1, upload_to="musica/canciones"),
            preserve_default=False,
        ),
    ]
