# Generated by Django 4.1 on 2024-03-02 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0002_artista_imagen"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="artista",
            name="redes_sociales",
        ),
    ]
