# Generated by Django 4.1 on 2024-04-30 08:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_artista_redes_sociales'),
        ('eventos', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_actuacion', models.TimeField()),
                ('rol', models.CharField(max_length=100)),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.artista')),
            ],
        ),
        migrations.AddField(
            model_name='evento',
            name='artistas',
            field=models.ManyToManyField(related_name='eventos', through='eventos.ArtistaEvento', to='booking.artista'),
        ),
        migrations.AddField(
            model_name='evento',
            name='edad_minima',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='evento',
            name='hora_fin',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='hora_inicio',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artistaevento',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.evento'),
        ),
    ]
